name: 'Pulumi'
on:
  - push

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Setup `node_modules`
        run: yarn install --frozen-lockfile
      - name: Copy State to Local
        run: |
          mkdir -p ~/.pulumi/stacks
          cp ./.pulumi/stacks/dev.json ~/.pulumi/stacks/
      - name: Pulumi Preview
        uses: pulumi/actions@v4
        timeout-minutes: 60
        with:
          command: preview
          stack-name: dev
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: '.'
          cloud-url: file://~
          diff: false
        env:
          PULUMI_CONFIG_PASSPHRASE: ''
          GOOGLE_CREDENTIALS: '{"type":"service_account"}'
